require:
  - rubocop-performance
  - rubocop-rake

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"
    - "config/performance.yml"

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/FetchEnvVar:
  Enabled: false
