require: rubocop-performance

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.5

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
