require: rubocop-performance

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
